spring.application.name=gtalent_spring_boot_260801

# 吃.env的資料
spring.config.import=optional:file:.env[.properties]

# 設定db連線
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Taipei}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 啟用 Flyway , Spring Boot 啟動時會自動跑 migration
spring.flyway.enabled=true
# 指定 migration SQL 放在哪裡
spring.flyway.locations=classpath:db/migration,classpath:db/seeder
spring.flyway.baseline-on-migrate=true

# Hibernate 驗證
spring.jpa.hibernate.ddl-auto=validate
# 把 Hibernate 執行的 SQL 印到 console
spring.jpa.show-sql=true
# 把印出來的 SQL 排版，變得比較好讀
spring.jpa.properties.hibernate.format_sql=true